# Logos
logo: swc_logo.svg
logoAlt: Software Carpentry
logoFooter: logo-white.svg
logoFooterAlt: Software Carpentry

footer_overview_text: Software Carpentry is a lesson program of The Carpentries. 

git_repo: https://github.com/swcarpentry/new-website

team_email: team@carpentries.org

# Other websites
dc-website: https://datacarpentry.org/
lc-website:  https://librarycarpentry.org/
carpentries-website: https://carpentries.org/

# Contact 
contact: https://carpentries.org/contact